#cloud-config

groups:
  - docker

timezone: 'Etc/UTC'
locale: "en_US.UTF-8"

users:
  - name: daugt
    groups: users, sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: true
    ssh_authorized_keys:
      - <public_ssh_key>

system_info:
  default_user:
    groups: [docker]

packages:
  - htop
  - git
  - curl
  - vim
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - unattended-upgrades
  - ufw
  - fail2ban
  - docker.io
  - nano
  - ncdu
  - apparmor

runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable
  - reboot

ssh_pwauth: false
disable_root: true

package_update: true
package_upgrade: true
package_reboot_if_required: true
unattended_upgrades:
  enable: true

services:
  enabled:
    - docker

swap:
  filename: /swapfile
  size: "1G"
  maxsize: "2G"
  
final_message: "The system is finally up!"